version: '3.7'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1-slim
    container_name: oracle_database
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=your_password
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
