version: '3.7'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    networks:
      - my_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8880:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_content:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - db
    networks:
      - my_network

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    ports:
      - "9990:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress2
      WORDPRESS_DB_PASSWORD: wordpress2_password
      WORDPRESS_DB_NAME: wordpress2_db
    volumes:
      - ./wp_content2:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - db
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8882:80"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:


volumes:
  db_data:
  wp_content:
  wp_content2:
