version: '3.7'

services:
  sql-server-2019:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: sql-server-2019
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc@123456789
    volumes:
      - sql-server:/var/opt/mssql

volumes:
  sql-server: