version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - ht-app-network

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - 8081:80
    networks:
      - ht-app-network

networks:
  ht-app-network:

volumes:
  mysql:
