version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306" # Change the port here
    networks:
      - ht-app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 8081:80
    networks:
      - ht-app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always
    networks:
      - ht-app-network

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: phpredisadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    networks:
      - ht-app-network
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8083:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - ht-app-network
networks:
  ht-app-network:

  # docker-compose up -d
